version: "3"

services:
  nginx:
    build: docker-duilds/nginx
    command: nginx -g "daemon off;"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/public
    links:
      - php
    ports:
      - "80:80"
  php:
    build:
      context: .
      dockerfile: DockerfilePhp
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/public
    command: php-fpm
    links:
      - db
      - cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: lumen
      DB_USERNAME: lumen
      DB_PASSWORD: secret
      MEMCACHED_HOST: cache
      CACHE_DRIVER: memcached
      PHP_XDEBUG_DEFAULT_ENABLE: 0
      PHP_XDEBUG_REMOTE_ENABLE: 0
      PHP_XDEBUG_REMOTE_HOST: 192.168.1.2
      PHP_XDEBUG_REMOTE_PORT: 9001
      PHP_XDEBUG_REMOTE_AUTO_START: 0
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_IDEKEY: docker
      PHP_XDEBUG_PROFILER_ENABLE: 0
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /tmp
  composer:
    image: composer:1.9.0
    volumes:
      - .:/app
    command: 'composer install'

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: lumen
      MYSQL_USER: lumen
      MYSQL_PASSWORD: secret
  cache:
    image: memcached
